services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_webhdfs_enabled=true        # ✅ enable WebHDFS API
    ports:
      - "9870:9870"   # Web UI + WebHDFS
      - "9000:9000"   # HDFS port
    volumes:
      - namenode-data:/hadoop/dfs/name
    healthcheck:                                   # ✅ health check for namenode
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 10s
      timeout: 5s
      retries: 5

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    depends_on:
      namenode:
        condition: service_healthy                 # ✅ wait for namenode ready
    volumes:
      - datanode-data:/hadoop/dfs/data

  app:
    build: .
    container_name: hdfs-app
    depends_on:
      namenode:
        condition: service_healthy
    environment:
      - HDFS_NAMENODE=namenode
    command: [ "sh", "-c", "sleep 25 && python app.py" ]  # ⏱️ more wait time
    volumes:
      - .:/app
    links:
      - namenode

volumes:
  namenode-data:
  datanode-data:
